services:
  aipersona-backend:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aipersona.rule=Host(`aipersona.pranta.dev`)"
      - "traefik.http.routers.aipersona.entrypoints=websecure"
      - "traefik.http.routers.aipersona.tls.certresolver=letsencrypt"
      - "traefik.http.services.aipersona.loadbalancer.server.port=8001"

networks:
  proxy:
    external: true
